name=Generador de Funciones
version=1.0.0
author=Bernardo de Legarreta Nava, Melissa Herrera Ruiz
maintainer=Bernardo de Legarreta Nava <bernardo.legarreta.n@gmail.com>, Melissa Herrera Ruiz <mherrera513@uvaq.edu.mx>
#sentence=
#paragraph=
#category=Signal Input/Output
url=https://github.com/m-herrera13/GeneradordeFunciones
#architectures=*
#depends=