name=Generador de Funciones
version=1.0.0
author=Bernardo de Legarreta Nava <bernardo.legarreta.n@gmail.com>, Melissa Herrera Ruiz <mherrera513@uvaq.edu.mx>
maintainer=Bernardo de Legarreta Nava <bernardo.legarreta.n@gmail.com>, Melissa Herrera Ruiz <mherrera513@uvaq.edu.mx>
sentence=Librería para generador de señales programables usando ESP32.
paragraph=Permite generar señales seno, cuadrada y triangular con control de frecuencia, amplitud y offset. Diseñada como parte de un generador de funciones basado en programación orientada a objetos.
category=Device Control
url=https://github.com/m-herrera13/GeneradordeFunciones
architectures=esp32 